dist: trusty
sudo: off
addons:
  apt:
    packages:
      - python-dev

language: go

git:
  depth: 1

branches:
  only:
    - master

env:
  global:
    - SOURCE_DIR="public"
    - DESTINATION_PATH="https://lisadiag351.blob.core.windows.net/public/"
    - CDN_RESOURCE_GROUP="lisa"
    - CDN_ENDPOINT_NAME="lisalinux"
    - CDN_PROFILE="lisa"

install: 
  - git clone https://github.com/subins2000/lisa
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ trusty main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list > ./microsoft-prod.list
  - sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
  - sudo apt-get update
  - sudo apt-get install apt-transport-https azcopy azure-cli
  - wget -d -O 'hugo.deb' 'https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb'
  - sudo dpkg -i hugo.deb

# Build the website
script:
  - mkdir themes
  - git submodule init
  - git submodule update
  - hugo
  - azcopy --source $SOURCE_DIR --destination $DESTINATION_PATH --dest-key $AZURE_STORAGE_ACCESS_KEY --recursive --quiet --set-content-type
  - az login --service-principal -u $AZURE_SERVICE_PRINCIPAL_APP_ID --password $AZURE_SERVICE_PRINCIPAL_APP_PASSWORD --tenant $AZURE_SERVICE_PRINCIPAL_TENANT
  - az cdn endpoint purge -g $CDN_RESOURCE_GROUP -n $CDN_ENDPOINT_NAME --profile-name $CDN_PROFILE --content-paths "/*"
 
